apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: helmcicd
  name: helmcicd
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: helmcicd
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: helmcicd
    spec:
      containers:
      - image: nginx
        name: nginx
