apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: helmcicd
    app.kubernetes.io/managed-by: Helm
  name: helmcicd
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.myservice.port }}
    protocol: TCP
    targetPort: 80
  selector:
    app: helmcicd
  type: {{ .Values.myservice.type }}
status:
  loadBalancer: {}
